export namespace DamageSourceInterface {
    export const none: number;
    export const override: number;
    export const contact: number;
    export const attack: number;
    export const projectile: number;
    export const suffocation: number;
    export const fall: number;
    export const fire: number;
    export const fire_tick: number;
    export const lava: number;
    export const drowning: number;
    export const block_explosion: number;
    export const entity_explosion: number;
    const _void: number;
    export { _void as void };
    export const suicide: number;
    export const magic: number;
    export const wither: number;
    export const starve: number;
    export const anvil: number;
    export const thorns: number;
    export const falling_block: number;
    export const piston: number;
    export const fly_into_wall: number;
    export const magma: number;
    export const fireworks: number;
    export const lightning: number;
    export const charging: number;
    export const temperature: number;
    export const freezing: number;
    export const stalactite: number;
    export const stalagmite: number;
    export const all: number;
}
export namespace DamageSource {
    const none_1: number;
    export { none_1 as none };
    const override_1: number;
    export { override_1 as override };
    const contact_1: number;
    export { contact_1 as contact };
    export const entity_attack: number;
    const projectile_1: number;
    export { projectile_1 as projectile };
    const suffocation_1: number;
    export { suffocation_1 as suffocation };
    const fall_1: number;
    export { fall_1 as fall };
    const fire_1: number;
    export { fire_1 as fire };
    const fire_tick_1: number;
    export { fire_tick_1 as fire_tick };
    const lava_1: number;
    export { lava_1 as lava };
    const drowning_1: number;
    export { drowning_1 as drowning };
    const block_explosion_1: number;
    export { block_explosion_1 as block_explosion };
    const entity_explosion_1: number;
    export { entity_explosion_1 as entity_explosion };
    const _void_1: number;
    export { _void_1 as void };
    const suicide_1: number;
    export { suicide_1 as suicide };
    const magic_1: number;
    export { magic_1 as magic };
    const wither_1: number;
    export { wither_1 as wither };
    const starve_1: number;
    export { starve_1 as starve };
    const anvil_1: number;
    export { anvil_1 as anvil };
    const thorns_1: number;
    export { thorns_1 as thorns };
    const falling_block_1: number;
    export { falling_block_1 as falling_block };
    const piston_1: number;
    export { piston_1 as piston };
    const fly_into_wall_1: number;
    export { fly_into_wall_1 as fly_into_wall };
    const magma_1: number;
    export { magma_1 as magma };
    const fireworks_1: number;
    export { fireworks_1 as fireworks };
    const lightning_1: number;
    export { lightning_1 as lightning };
    const charging_1: number;
    export { charging_1 as charging };
    const temperature_1: number;
    export { temperature_1 as temperature };
    const freezing_1: number;
    export { freezing_1 as freezing };
    const stalactite_1: number;
    export { stalactite_1 as stalactite };
    const stalagmite_1: number;
    export { stalagmite_1 as stalagmite };
    export const fatal: number;
}
export default class DamageData {
    constructor(cause: any, damage: any);
    cause: any;
    damage: any;
}
