export declare let originalConsole: Console;
export declare let logLevel: number;
export declare class Logger {
    static LEVEL_FATAL: number;
    static LEVEL_ERROR: number;
    static LEVEL_WARN: number;
    static LEVEL_INFO: number;
    static LEVEL_DEBUG: number;
    static LEVEL_TRACE: number;
    static log(...args: any[]): void;
    0: (...args: string[]) => void;
    1: (...args: string[]) => void;
    2: (...args: string[]) => void;
    3: (...args: string[]) => void;
    4: (...args: string[]) => void;
    5: (...args: string[]) => void;
    fatal: (...args: string[]) => void;
    error: (...args: string[]) => void;
    warn: (...args: string[]) => void;
    info: (...args: string[]) => void;
    debug: (...args: string[]) => void;
    trace: (...args: string[]) => void;
    f: (...args: string[]) => void;
    e: (...args: string[]) => void;
    w: (...args: string[]) => void;
    i: (...args: string[]) => void;
    d: (...args: string[]) => void;
    t: (...args: string[]) => void;
    warning: (...args: string[]) => void;
    err: (...args: string[]) => void;
    fail: (...args: string[]) => void;
    ex: (...args: string[]) => void;
    notice: (...args: string[]) => void;
    log: (...args: string[]) => void;
    severe: (...args: string[]) => void;
    name: any;
    constructor(name?: string);
}
export default Logger;
export declare const log: typeof Logger.log;
declare const defaultLogger: Logger;
export { defaultLogger as console };
