import "./test/eventTest.js";
import "./test/schedulerTest1.js";
import "./test/schedulerTest2.js";
import "./test/getPlayerTest.js";
import "./test/schedulerTest3.js";
import "./test/scoreboard_test.js";
import "./test/module_load.js";
import "./test/vanillaEventTest.js";
import "./test/itemCreate0.js";
