import "./WatchBird.js";
import { Entity, Player, SimulatedPlayer, YoniEntity, YoniPlayer, YoniSimulatedPlayer } from "./entity.js";
import { Minecraft, Gametest, MinecraftGui, VanillaWorld, VanillaScoreboard, VanillaEvents, dim, runTask } from "./basis.js";
import { Logger, log } from "./util/Logger.js";
import { World } from "./world.js";
import { Command } from "./command.js";
import { EventListener, EventTypes, EventSignal } from "./event.js";
import { Scoreboard, Entry, Objective } from "./scoreboard.js";
import { Schedule, YoniScheduler } from "./schedule.js";
import { isDebug } from "./debug.js";
import { ChatCommand } from "./util/ChatCommand.js";
import { Location } from "./Location.js";
declare const Utils: {};
export { isDebug, EventTypes, EventListener, EventSignal, Scoreboard, Objective, Entry, World, dim, Minecraft, MinecraftGui, Gametest, VanillaWorld, VanillaEvents, VanillaScoreboard, runTask, Logger, log, YoniScheduler, Schedule, Command, ChatCommand, Player, Entity, SimulatedPlayer, YoniEntity, YoniPlayer, YoniSimulatedPlayer, Utils, Location };
